src/Entity/Nir.php
<?php

namespace App\Entity;

use App\Model\NirProducts;
use App\Repository\NirRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=NirRepository::class)
 */
class Nir
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $supplier;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $receiver;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nir_serie;

    /**
     * @ORM\Column(type="integer")
     */
    private $nir_number;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $invoice_number;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $reception_committee;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $stock_manager;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $totals;

    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    /**
     * @return Collection|NirProducts[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    /**
     * @param NirProducts $products
     * @return Nir
     */
    public function addProducts(NirProducts $products): self
    {
        if(!$this->products->contains($products)){
            $this->products[] = $products;
        }
        return $this;
    }

    public function setProducts(ArrayCollection $products): self
    {
        $this->products = $products;

        return $this;
    }

    public function removeBilledProducts(NirProducts $products)
    {
        $this->products->removeElement($products);

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSupplier(): ?string
    {
        return $this->supplier;
    }

    public function setSupplier(string $supplier): self
    {
        $this->supplier = $supplier;

        return $this;
    }

    public function getReceiver(): ?string
    {
        return $this->receiver;
    }

    public function setReceiver(string $receiver): self
    {
        $this->receiver = $receiver;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getNirSerie(): ?string
    {
        return $this->nir_serie;
    }

    public function setNirSerie(string $nir_serie): self
    {
        $this->nir_serie = $nir_serie;

        return $this;
    }

    public function getNirNumber(): ?int
    {
        return $this->nir_number;
    }

    public function setNirNumber(int $nir_number): self
    {
        $this->nir_number = $nir_number;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getReceptionCommittee(): ?string
    {
        return $this->reception_committee;
    }

    public function setReceptionCommittee(?string $reception_committee): self
    {
        $this->reception_committee = $reception_committee;

        return $this;
    }

    public function getStockManager(): ?string
    {
        return $this->stock_manager;
    }

    public function setStockManager(?string $stock_manager): self
    {
        $this->stock_manager = $stock_manager;

        return $this;
    }

    public function getTotals(): ?string
    {
        return $this->totals;
    }

    public function setTotals(string $totals): self
    {
        $this->totals = $totals;

        return $this;
    }

    public function getInvoiceNumber(): ?string
    {
        return $this->invoice_number;
    }

    public function setInvoiceNumber(string $invoice_number): self
    {
        $this->invoice_number = $invoice_number;

        return $this;
    }

    public function getComments(): ?string
    {
        return $this->comments;
    }

    public function setComments(?string $comments): self
    {
        $this->comments = $comments;

        return $this;
    }
}

src/Form/NirType.php
<?php

namespace App\Form;

use App\Entity\Nir;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class NirType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('supplier', TextType::class,[
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Supplier'
                ],
                'label' => false,
            ])
            ->add('receiver', TextType::class,[
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Receiver'
                ],
                'label' => false
            ])
            ->add('invoiceNumber', TextType::class,[
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Invoice'
                ],
                'label' => false
            ])
            ->add('date', DateType::class,[
                'attr' => [
                    'class' => 'form-control'
                ],
                'widget' => 'single_text',
                'label' => false
            ])
            ->add('nir_serie', HiddenType::class,[
                'data' => 'N'
            ])
            ->add('reception_committee',TextType::class,[
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'reception committee'
                ],
                'label' => false
            ])
            ->add('stock_manager',TextType::class,[
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'stock manager'
                ],
                'label' => false
            ])
            ->add('comments',TextType::class,[
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'comments'
                ],
                'label' => false,
                'required'   => false,
            ])
            ->add('products', CollectionType::class,[
                'label' => false,
                'entry_type' => NirProductsType::class,
                'entry_options' => [
                    'label' => false,
                ],
                'by_reference' =>false,
                'allow_add' => true,
                'allow_delete' => true
            ])
            ->add('save', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Nir::class,
        ]);
    }
}

src/Controller/NirController.php
<?php

namespace App\Controller;

use App\Entity\Nir as NirEntity;
use App\Form\NirType;
use App\Service\NirServiceInterface;
use App\Service\StockServiceInterface;
use Doctrine\Common\Collections\Collection;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class NirController
 * @package App\Controller
 * @Route("/nir")
 */
class NirController extends AbstractController
{

    /** @var StockServiceInterface  */
    private $stockService;

    /**
     * @var NirServiceInterface
     */
    private $nirService;

    public function __construct(StockServiceInterface $stockService, NirServiceInterface $nirService)
    {
        $this->stockService = $stockService;
        $this->nirService = $nirService;
    }

    /**
     * @Route("/create", name="create_nir")
     * @param Request $request
     * @return Response
     */
    public function index(Request $request): Response
    {
        $nir = new NirEntity();

        $form = $this->createForm(NirType::class, $nir);
        $form->handleRequest($request);

        if($form->isSubmitted())
        {
            $this->nirService->create($nir);
            $this->addToStock($nir->getProducts());
        }

        return $this->render('nir/index.html.twig', [
            'form' => $form->createView(),
            'stock' => $this->stockService->getFullStock()
        ]);
    }

    /**
     * @Route("/list", name="list_nirs")
     * @return Response
     */
    public function listNirs(): Response
    {
        return $this->render('nir/list.html.twig', [
            'nirs' => $this->nirService->list()
        ]);
    }

    /**
     * @Route("/delete/{id}", name="delete_nir")
     * @param int $id
     * @return RedirectResponse
     */
    public function delete(int $id): RedirectResponse
    {
        $this->nirService->delete($id);

        return $this->redirectToRoute('list_nirs');
    }

    /**
     * @Route("/view/{id}", name="view_nir")
     * @param int $id
     * @return Response
     */
    public function view(int $id): Response
    {
        $nir = $this->nirService->getSingleNirEntity(['id' => $id]);

        return $this->render('/nir/template.html.twig', [
            'nir' => $nir,
            'products' => $this->getNirProductModels($nir->getContent()),
            'totals' => json_decode($nir->getTotals())
        ]);
    }

    private function getNirProductModels(string $content): array
    {
        $nirProductsArr = [];

        foreach (json_decode($content) as $product){
            $nirProductsArr[] = $this->nirService->getNirProductsModel($product);
        }

        return $nirProductsArr;
    }

    /* upload products from stock */
    private function addToStock(Collection $products): void
    {
        /** @var  $product \App\Model\NirProducts */
        foreach ($products->getIterator() as $product)
        {
            $getProduct = $this->stockService->getSingleStockEntity(['hash' => $product->getHash()]);
            if($getProduct)
            {
                $newQuantity =  number_format((float)$getProduct->getQty() + $product->getQty(),
                    3, '.', '');

                $getProduct->setQty($newQuantity);
                $this->stockService->changeOrAddToStock($getProduct);
            } else
                { $this->stockService->changeOrAddToStock($getProduct); }
        }
    }

}

templates/nir/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello NirController!{% endblock %}

{% block body %}
    <div class="card">
        {{ form_start(form) }}
        <div class="card-header"></div>
        <div class="card-body">
            <table id="example" class="display">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>UM</th>
                    <th>Qty</th>
                    <th>Price</th>
                </tr>
                </thead>
                <tbody>
                {% for row in stock %}
                    <tr>
                        <td>{{ row.getName }}</td>
                        <td>{{ row.getUm }}</td>
                        <td>{{ row.getQty }}</td>
                        <td>{{ row.getPrice }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="card-header col-sm-9 col-sm-offset-2" style="margin:20px 0 0 20px;">
            <table id="display_selected_products" class="display" style="width:100%"><thead style="border-bottom: solid 1px;"><tr><th>Name</th><th>Um</th><th>Type</th><th>Qty</th><th>Price</th><th>Value</th><th>Obs</th></tr></thead><tbody></tbody></table>
        </div>
        <div class="col-sm-5 col-sm-offset-2" style="margin:20px 0 0 20px; ">
            <div style="height: 50px;">{{ form_row(form.supplier) }}</div>
            <div style="height: 50px;">{{ form_row(form.receiver) }}</div>
            <div style="height: 50px;">{{ form_row(form.invoiceNumber) }}</div>
            <div style="height: 50px;">{{ form_row(form.date) }}</div>
            <div style="height: 50px;">{{ form_row(form.reception_committee) }}</div>
            <div style="height: 50px;">{{ form_row(form.stock_manager) }}</div>
            <div style="height: 50px;">{{ form_row(form.comments) }}</div>
        </div>
        <div class="col-sm-5 col-sm-offset-2" style="margin:20px 0 0 20px;">
            <div class="row g-3">
                <div>
                    <div class="col">
                        <input type="text" id="name" class="form-control" placeholder="Product" aria-label="Product">
                    </div>
                </div>
                <div class="col-sm">
                    <input type="text" id="um" class="form-control" placeholder="UM" aria-label="Um">
                </div>
                <div class="col-sm">
                    <input type="text" id="qty" class="form-control" placeholder="Qty" aria-label="Qty">
                </div>
                <div class="col-sm">
                    <select class="form-control" id="type">
                        <option value="inventar">Inventar</option>
                        <option value="marfuri">Marfuri</option>
                        <option value="consumabile">Consumabile</option>
                    </select>
                </div>
                <div class="col-sm">
                    <input type="text" id="price" class="form-control" placeholder="Price" aria-label="Price">
                </div>
                <div>
                    <div class="col-sm-6">
                        <input type="text" id="obs" class="form-control" placeholder="Obs." aria-label="Obs">
                    </div>
                </div>
                <div><button type="button" id="add_single_product"><i class="fa fa-plus" style="font-size:36px"></i></button></div>
            </div>
            <div class="card-body" id="stock-list" data-prototype="{{ form_widget(form.products.vars.prototype)|e('html_attr') }}">
                <div class="panel" style="display: block;">

                </div>
            </div>
        </div>
        <div class="card-footer">{{ form_row(form.save) }}</div>
        {{ form_end(form) }}
    </div>

    <script src="../js/app2.js"></script>
{% endblock %}

templates/nir/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserProfileController!{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-header"></div>
        <div class="card-body">
            <table id="list_nirs" class="display">
                <thead>
                <tr>
                    <th>No.</th>
                    <th>Document</th>
                    <th>Supplier</th>
                    <th>Date</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for key, row in nirs %}
                    <tr>
                        <td>{{ key + 1 }}</td>
                        <td>{{ row.getNirSerie }}:{{ "%06d"|format(row.getNirNumber) }}</td>
                        <td>{{ row.getSupplier }}</td>
                        <td>{{ row.getDate|date('Y-m-d') }}</td>
                        <td align="right"><a href="{{ path('view_nir' ,{"id": row.getId}) }}">
                                <button type="button" id=""><i class="fa fa-eye" style="font-size:18px"></i></button></a>
                        </td>
                        <td align="right"><a href="{{ path('delete_nir' ,{"id": row.getId}) }}">
                                <button type="button" id=""><i class="fa fa-trash" style="font-size:18px"></i></button></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="card-footer"></div>
    </div>
    <script>
        $(document).ready(function() {
            $('#list_nirs').DataTable();
        });
    </script>
{% endblock %}

templates/nir/template.html.twig
<!DOCTYPE html>
<html>
<head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

    <script>
        window.onload = function () {
            document.getElementById("download").addEventListener("click", () => {
                const invoice = this.document.getElementById("invoice");
            var opt = {
                margin: 0,
                filename: '{{ nir.getNirSerie }}_{{ "%06d"|format(nir.getNirNumber) }}',
                image: { type: 'jpeg', quality: 0.98 },
                html2canvas: {
                    dpi: 600,
                    scale:4,
                    letterRendering: true,
                    useCORS: true
                },
                jsPDF: { unit: 'in', format: 'A4', orientation: 'landscape' }
            };
            html2pdf().from(invoice).set(opt).save();
        })
        }
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.2/html2pdf.bundle.js"></script>
    <style>
        body {
            margin: 0;
            line-height: 1.5385;
            color: #333;
            text-align: left;
            background-color: #000
        }

        .card {
            position: relative;
            display: -ms-flexbox;
            display: flex;
            -ms-flex-direction: column;
            flex-direction: column;
            min-width: 0;
            word-wrap: break-word;
            background-color: #fff;
            background-clip: border-box;
            border: 1px solid rgba(0, 0, 0, .125);
            border-radius: .1875rem
        }

        .invoice-title h2, .invoice-title h3 {
            display: inline-block;
        }

        .table > tbody > tr > .no-line {
            border-top: none;
        }

        .table > thead > tr > .no-line {
            border-bottom: none;
        }

        .table > tbody > tr > .thick-line {
            border-top: 2px solid;
        }
    </style>

</head>
<body>
<div class="offset-xl-2 col-xl-8 col-lg-12 col-md-12 col-sm-12 col-12 padding">
    <div class="col-md-12">
        <div align="right"><button class="btn btn-primary" id="download">Download</button></div>
        <div class="card" style="margin: 5px 0 0 0; border: none;" id="invoice">
            <div align="center" style="font-size: 19px;"><strong>NOTA DE RECEPTIE</strong></div>
            <br>
            <br>
            <table style="width: 70%; font-size: 11px;" align="center">
                <tbody>
                <tr>
                    <td>
                        Unitate: {{ nir.receiver }}
                    </td>
                    <td align="right">NIR: {{ nir.getNirSerie }} {{ "%06d"|format(nir.getNirNumber) }}</td>
                </tr>
                <tr>
                    <td>
                        Gestiunea:Cantitativ Valoric cu TVA
                    </td>
                    <td align="right">Data: {{ nir.date|date('Y-m-d') }}</td>
                </tr>
                <tr>
                    <td>
                        Furnizor: {{ nir.supplier }}
                    </td>
                    <td align="right">Factura: {{ nir.invoiceNumber }}</td>
                </tr>
                </tbody>
            </table>
            <br>
            <table style="border: 1px solid; font-size: 9px; margin: 0 2px 0 2px;">
                <thead>
                <tr>
                    <th style="border-bottom: 1px solid;">Nr. Crt.</th>
                    <th style="border-bottom: 1px solid;">Denumire Produs/Serviciu/Cod</th>
                    <th style="border-bottom: 1px solid;">Tip Produs/Serviciu</th>
                    <th style="border-bottom: 1px solid;">U.M.</th>
                    <th style="border-bottom: 1px solid;">Cantitate</th>
                    <th style="border-bottom: 1px solid;">Pret Unitar(Lei)</th>
                    <th style="border-bottom: 1px solid;">Valoare(Lei)</th>
                    <th style="border-bottom: 1px solid;">Observatii</th>
                </tr>
                </thead>
                <tbody>
                {% for key, line in products %}
                    <tr>
                        <td style="border-bottom: solid 1px; width: 3%; text-align: center;">{{ key+1 }}</td>
                        <td style="border-bottom: solid 1px;">{{ line.getName }}</td>
                        <td style="border-bottom: solid 1px;">{{ line.getType }}</td>
                        <td style="border-bottom: solid 1px;">{{ line.um }}</td>
                        <td style="border-bottom: solid 1px;">{{ line.qty }}</td>
                        <td style="border-bottom: solid 1px;">{{ line.price }}</td>
                        <td style="border-bottom: solid 1px;">{{ line.getValue }}</td>
                        <td style="border-bottom: solid 1px;">{{ line.obs }}</td>
                    </tr>
                {% endfor %}
                <tr>
                    <td height="10"></td>
                </tr>
                <tr>
                    <td colspan="4"></td>
                    <td><strong>Total Inventar:</strong></td>
                    <td><strong>{{ totals.inventar }} Lei</strong></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td colspan="4"></td>
                    <td><strong>Total Consumabile:</strong></td>
                    <td><strong>{{ totals.consumabile }} Lei</strong></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td colspan="4"></td>
                    <td><strong>Total Materiale/Marfuri:</strong></td>
                    <td><strong>{{ totals.marfuri }} Lei</strong></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td height="10"></td>
                </tr>
                <tr>
                    <td></td>
                    {% set total = totals.marfuri +  totals.consumabile +  totals.inventar %}
                    <td><strong>TOTAL NIR: {{ total }} Lei</strong></td>
                    <td colspan="1" align="right" height=" 50"><strong>Observatii: </strong> </td>
                    <td colspan="5" style="border: solid 1px; border-bottom: none; border-right: none;
                        padding-top: 5px; padding-left: 5px;">
                        {{ nir.getComments }}
                    </td>
                    <td colspan="5" style="border: 1px none;border-top-style: solid;"></td>
                </tr>
                </tbody>
            </table>
            <br>
            <br>
            <br>
            <br>
            <table style="height: 100px;font-size: 9px; margin: 0 2px 0 2px;">
                <thead>
                <tr>
                    <th style="border-left: solid 1px; border-top: solid 1px; border-right: solid 1px; text-align: center;">
                        Numele si Prenumele Membrilor Comisiei de Receptie
                    </th>
                    <th style="border-top: solid 1px;border-right: solid 1px; text-align: center;">
                        Semnatura
                    </th>
                    <th style="border-top: solid 1px;border-right: solid 1px; text-align: center;">
                        Numele si Prenumele Gestionarului
                    </th>
                    <th style="border-top: solid 1px;border-right: solid 1px; text-align: center;">
                        Semnatura
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td valign="top" style="border-bottom: solid 1px;border-left: solid 1px;border-top: solid 1px;
                        padding-top: 5px; padding-left: 5px;">
                        <strong>{{ nir.getReceptionCommittee }}</strong><br>
                    </td>
                    <td style="border-bottom: solid 1px;border-left: solid 1px;border-top: solid 1px;"></td>
                    <td valign="top" style="border-bottom: solid 1px;border-left: solid 1px;border-top: solid 1px;
                        padding-top: 5px; padding-left: 5px;">
                        <strong>{{ nir.stockManager }}</strong>
                    </td>
                    <td style="border: 1px solid;"></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
</body>
</html>